server:
  port: 9088

spring:
  application:
    name: world-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/world?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: antonio3a
    password: Antonio.3A
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9180/realms/antonio3a-realm
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs

logging:
  level:
    org:
      hibernate:
        sql: debug

springdoc:
  swagger-ui:
    use-root-path: true
    tags-sorter: alpha
    operations-sorter: alpha
    displayRequestDuration: true
