server:
  port: 443
  ssl:
    enabled: true
    key-alias: world-api
    key-store: keystore.p12
    key-store-type: PKCS12
    key-store-password: Antonio.3A

spring:
  graphql:
    graphiql:
      enabled: true
  application:
    name: world-api
  config:
    import: optional:vault://
  cloud:
    vault:
      enabled: false
      uri: ${env.vault.host}
      authentication: token
      token: ${env.vault.token}
      kv:
        enabled: true
        backend: antonio3a
        default-context: 3A
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${env.mysql.host}/world?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${env.main.username}
    password: ${env.main.password}
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${env.keycloak.realm.uri}
          jwk-set-uri: ${env.keycloak.protocol.uri}/certs

logging:
  level:
    org:
      hibernate:
        sql: debug

springdoc:
  swagger-ui:
    use-root-path: true
    tags-sorter: alpha
    operations-sorter: alpha
    displayRequestDuration: true
    oauth:
      realm: ${env.keycloak.realm.name}
      client-id: ${env.keycloak.client.world-api.id}
      use-pkce-with-authorization-code-grant: true

oauth-flow:
  token-url: ${env.keycloak.protocol.uri}/token
  refresh-token-url: ${env.keycloak.protocol.uri}/token
  authorization-url: ${env.keycloak.protocol.uri}/auth

env:
  main:
    host: ${3A_3A_HOST}
    username: ${3A_3A_USERNAME}
    password: ${3A_3A_PASSWORD}
  keycloak:
    host: ${3A_KEYCLOAK_HOST}
    protocol:
      uri: ${env.keycloak.realm.uri}/protocol/openid-connect
    realm:
      name: ${3A_KEYCLOAK_REALM_NAME}
      uri: http://${env.keycloak.host}/realms/${env.keycloak.realm.name}
    client:
      world-api:
        id: ${3A_KEYCLOAK_WORLD_API_CLIENT_ID}
  mysql:
    host: ${3A_MYSQL_HOST}
  vault:
    host: ${3A_VAULT_HOST}
    token: ${3A_VAULT_TOKEN}
  zipkin:
    host: ${3A_ZIPKIN_HOST}
