server:
  port: 443
  ssl:
    enabled: true
    key-alias: world-api
    key-store: keystore.p12
    key-store-type: PKCS12
    key-store-password: Antonio.3A

spring:
  graphql:
    graphiql:
      enabled: true
  application:
    name: world-api
  config:
    import: optional:vault://
  cloud:
    vault:
      uri: ${env.vault.host}
      authentication: token
      token: ${env.vault.token}
      kv:
        backend: secrets
        default-context: application
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${env.mysql.host}/world?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${env.mysql.username}
    password: ${env.mysql.password}
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${env.keycloak.realm.uri}
          jwk-set-uri: ${env.keycloak.protocol.uri}/certs

logging:
  level:
    org:
      hibernate:
        sql: debug

management:
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    git:
      mode: full

  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${env.zipkin.host}/api/v2/spans

springdoc:
  swagger-ui:
    use-root-path: true
    tags-sorter: alpha
    operations-sorter: alpha
    displayRequestDuration: true
    oauth:
      realm: ${env.keycloak.realm.name}
      client-id: ${env.oauth2.client-id}
      use-pkce-with-authorization-code-grant: true

env:
  keycloak:
    host: ${KEYCLOAK_HOST}
    protocol:
      uri: ${env.keycloak.realm.uri}/protocol/openid-connect
    realm:
      name: ${KEYCLOAK_REALM_NAME}
      uri: http://${env.keycloak.host}/realms/${env.keycloak.realm.name}
  mysql:
    host: ${MYSQL_HOST}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  oauth2:
    client-id: ${KEYCLOAK_WORLD_API_CLIENT_ID}
    authorization-url: ${env.keycloak.protocol.uri}/auth
    token-url: ${env.keycloak.protocol.uri}/token
  vault:
    host: ${3A_VAULT_HOST}
    token: ${3A_VAULT_TOKEN}
  zipkin:
    host: ${ZIPKIN_HOST}

info:
  app:
    ame: ${spring.application.name}
    version: 0.0.1
    description: ${spring.application.name} application
