server:
  port: 443
  ssl:
    enabled: true
    key-alias: world-api
    key-store: keystore.p12
    key-store-type: PKCS12
    key-store-password: Antonio.3A

spring:
  graphql:
    graphiql:
      enabled: true
  application:
    name: world-api
  config:
    import: optional:vault://
  cloud:
    vault:
      enabled: false
      uri: ${3A_3A_HOST}:8200
      authentication: token
      token: fdbtdg5getg
      kv:
        enabled: true
        backend: antonio3a
        default-context: 3A
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${3A_3A_HOST}/world?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${3A_3A_USERNAME}
    password: ${3A_3A_PASSWORD}
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${keycloak.realm.uri}
          jwk-set-uri: ${keycloak.realm.uri}/protocol/openid-connect/certs

logging:
  level:
    org:
      hibernate:
        sql: debug

springdoc:
  swagger-ui:
    use-root-path: true
    tags-sorter: alpha
    operations-sorter: alpha
    displayRequestDuration: true
    oauth:
      realm: ${keycloak.realm.name}
      client-id: ${3A_WORLD_API_CLIENT_ID}
      use-pkce-with-authorization-code-grant: true

oauth-flow:
  token-url: ${keycloak.realm.uri}/protocol/openid-connect/token
  refresh-token-url: ${keycloak.realm.uri}/protocol/openid-connect/token
  authorization-url: ${keycloak.realm.uri}/protocol/openid-connect/auth

keycloak:
  realm:
    name: antonio3a-realm
    uri: http://${3A_3A_HOST}:9180/realms/${keycloak.realm.name}